-- Per-buyer list of supporting documents that workers must photograph alongside
-- the primary tax invoice. is_buyer_generated = true means the buyer hands over
-- this document themselves (e.g. Vishal Mega Mart's Gate Entry / Discrepancy Note
-- is generated by their system; the worker just photographs what the store gives them).
-- is_buyer_generated = false means the vendor must produce/attach the doc.
CREATE TABLE IF NOT EXISTS buyer_document_requirements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    buyer_id UUID NOT NULL REFERENCES buyers(id) ON DELETE CASCADE,
    document_type VARCHAR(50) NOT NULL,
    label VARCHAR(100) NOT NULL,
    is_buyer_generated BOOLEAN NOT NULL DEFAULT false,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_buyer_doc_req UNIQUE (organization_id, buyer_id, document_type)
);
CREATE INDEX IF NOT EXISTS idx_buyer_doc_req_buyer ON buyer_document_requirements(buyer_id);

ALTER TABLE buyer_document_requirements ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_buyer_doc_requirements_policy ON buyer_document_requirements
    USING (organization_id = NULLIF(current_setting('app.current_tenant_id', true), '')::UUID);

GRANT SELECT, INSERT, UPDATE, DELETE ON buyer_document_requirements TO app_user;
